### ISSUE TITLE
vTaskDelay, ERROR_LED_PIN

### ISSUE THREAD

**Issue by dsyleixa** [BriscoeTech/Arduino-FreeRTOS-SAMD51#3]
just out of interest:
why do you use 
vTaskDelay( us / portTICK_PERIOD_US ) instead of sleep or usleep (which is standard C) or delay() (Arduinish)
and
ERROR_LED_PIN  13 vs. 2 instead of LED_BUILTIN (which is cross-board-compatible)
?

**Comment by BriscoeTech** [comment]
Hello dsyleixa,

The sleep or usleep functions are actually not part of the C or C++ language standard at all, these functions are part of the POSIX standard which assumes you are running on a os like Linux and adds C/C++ functions that integrate with your os features. FreeRtos is not a traditional os and does not attempt to implement alot of things that Windows or Linux would offer. Instead FreeRtos has implemented and documented their own timing functions instead of trying to conform to a standard that it could never fully implement.

Here is a awesome reference for how to use the FreeRtos timing functions https://www.freertos.org/a00127.html

The reason I use a #define for my leds is for flexibility. You can define ERROR_LED_PIN  to be LED_BUILTIN if you like
 that is totally allowed. I make alot of custom boards, and have multiple leds hooked to different pins for debugging and this gives me the flexibility to make the code use any pin not just the built in led. Also the LED_BUILTIN was introduced afew years ago, and I remember running into Arduino ports that did not implement LED_BUILTIN. I think this has been well adopted by now and probably not a issue anymore.

Good luck! Hope this helps :-)

**Comment by dsyleixa** [comment]
thanks for your reply!
as to 
vTaskDelay( us / portTICK_PERIOD_US ) , it's hardly understandable, why don't you use then delay() or millis() instead?

OTOH, the RTOS used by ESP32 also uses std::chrono and std::thread, e.g.
std::this_thread::sleep_for(std::chrono::milliseconds(500));
see: 
https://github.com/dsyleixa/Arduino/blob/master/ESP32_Test/esp32_stdthread_001/esp32_stdthread_001.ino
https://github.com/dsyleixa/Arduino/blob/master/ESP32_Test/esp32_stdthread_002/esp32_stdthread_002.ino

**Comment by trlafleur** [comment]
ESP32 is using ver 8.2.x of FreeRTOS with there own enhancements...

Also, vTaskDelay( us / portTICK_PERIOD_US ) is what is documented in the
FreeRTOS manual, you can always change it..

#define delay1   vTaskDelay

or

void delay1 (uint32_t us)
{
   vTaskDelay( us / portTICK_PERIOD_US );
}

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by dsyleixa** [comment]
ok, but it would be appreciated to have the ESP32-enhancement for crossboard-code-compatibility though

**Comment by BriscoeTech** [comment]
> vTaskDelay( us / portTICK_PERIOD_US ) , it's hardly understandable

Hehehe it is a little hard to read first time, that is one reason I wrapped them to something more understandable and arduino like, see the basic examples for myDelayMs()

> why don't you use then delay()

Someone has brought this up before, and there is a big misconception about how delay() works, and why the ESP arduino cores are different and unique when being compared with all the other arduino cores, since it also integrating FreeRtos.

Delay is a standard arduino function that every arduino core implements, but there is no one correct way to implement these functions. Traditionally on the Atmega processors this was done as just a time wasting loop, insert a whole bunch of Nops assembly instructions in a for loop and that was the delay. This works quite well.... assuming you are not doing any kind of multitasking or intense interrupt handling, and that has led alot of people had a love/hate relationship with the delay() function early on. **The way delay is implemented depends on the arduino core that is implementing it**. For the samd21 and samd51 versions that came later, the arduino core and then latter forked sparkfun and adafruit cores have cleaned this up alot, and it is more interrupt driven and plays nicely with lots of interrupts, but still not designed with a rtos in mind. Where alot of misconception is when the Esp cores were being developed, they were developing the core to also have FreeRtos built right into it. Because of this, they decided to make their delay() not only interrupt friendly, but also work directly with their built in FreeRtos functions. This is not the case for the Samd21 and Samd51 cores, FreeRtos is a separate optional library you are including. To do the same thing that the Esp cores are providing, you will have to re implement the arduino cores with the rtos built in. 

So the real answer is if you want **to make truly cross-comparable FreeRtos code, you should never use the delay() command as this is Arduino core dependent. Only use the commands defined in the FreeRtos documentation since this has been standardized for all FreeRtos code.**  

I think it was a wonderful thing that the esp core made FreeRtos built in and were able to make delay FreeRtos friendly, but there is no way to make that a standard without redoing every arduino core to have FreeRtos built in as well. In a way the Esp core delay() is a oversimplification and doing everyone a disservice by this convenience, because now everyone assumes delay() should work the same when they port their FreeRtos code to a different Arduino processor and that is not the case at all. 

> or millis() instead

millis() return the current tick count of a hardware timer, and this you can use this with FreeRtos without any issues. I use this to see how long it takes to run processing intensive chucks of code and generate runtime statistics print statements. 

Bad part about millis is people end up trying to use it to implement a type of multi threaded delay: making a while loop and polling this counter and wasting alot of processing time until so much time has gone by meanwhile doing stuff. You had to do this on the older Atmega chips because there was no rtos and they were tying to do multiple things at once. Poling does not give you the advantages FreeRtos delays do which will block a task, and will run other threads until the delay is complete. This gives you a very efficient multi threadeded solution to a problem instead of trying to cram multiple things into one while loop. The millis() command is not a good replacement for a proper multi tasked solution because of the poling and its not as scalable like multiple threaded solutions are.

> OTOH, the RTOS used by ESP32 also uses std::chrono and std::thread, e.g.
std::this_thread::sleep_for(std::chrono::milliseconds(500));

That is interesting, have not seen this yet. It looks like they wrapped the std::thread library to interface with their FreeRtos core code. I will have to take a look at this someday :-)

Again, an awesome nicety that the esp team has done, but the std::thread is not part of the FreeRtos standard and you cannot assume every FreeRtos port also implemented this optional wrapping.

One of my professors had a saying that I have since taken to heart: "Standards are great, there are plenty of them to choose from......" contradicting the reason we make standards :-P. Sadly its kind of true, there are too many ways to do things and once you jump ship on a standard your are stuck using something else since they do not follow the same philosophies.

Hope this helps clear up why things are implemented the way they are. Very good questions :-)

**Comment by dsyleixa** [comment]
thanks a lot for your very detailed and very understandable explanations! Gladly looking forward when trying it out!

PS,
perhaps you could include the delay-wrappers in your .h file publicly by default like
thr_delay(uint32_t ms) aka thr_msleep(uint32_t ms)
thr_sleep(uint32_t sec)
thr_usleep(uint32_t microsec)
